extensions = {
    # No name
    'noname': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Other/Uncategorized",
    # Audio
    '.aif': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Media/Audio",
    '.cda': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Media/Audio",
    '.mid': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Media/Audio",
    '.midi': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Media/Audio",
    '.mp3': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Media/Audio",
    '.mpa': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Media/Audio",
    '.ogg': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Media/Audio",
    '.wav': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Media/Audio",
    '.wma': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Media/Audio",
    '.wpl': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Media/Audio",
    '.m3u': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Media/Audio",
    # Text
    '.txt': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Text/TextFiles",
    '.doc': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Text/Microsoft/Word",
    '.docx': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Text/Microsoft/Word",
    '.odt ': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Text/TextFiles",
    '.pdf': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Text/PDF",
    '.rtf': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Text/TextFiles",
    '.tex': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Text/TextFiles",
    '.wks ': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Text/TextFiles",
    '.wps': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Text/TextFiles",
    '.wpd': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Text/TextFiles",
    # Video
    '.3g2': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Media/Video",
    '.3gp': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Media/Video",
    '.avi': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Media/Video",
    '.flv': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Media/Video",
    '.h264': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Media/Video",
    '.m4v': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Media/Video",
    '.mkv': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Media/Video",
    '.mov': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Media/Video",
    '.mp4': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Media/Video",
    '.mpg': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Media/Video",
    '.mpeg': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Media/Video",
    '.rm': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Media/Video",
    '.swf': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Media/Video",
    '.vob': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Media/Video",
    '.wmv': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Media/Video",
    # Images
    '.ai': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Media/Images",
    '.bmp': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Media/Images",
    '.gif': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Media/Images",
    '.ico': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Media/Images",
    '.jpg': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Media/Images",
    '.jpeg': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Media/Images",
    '.png': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Media/Images",
    '.ps': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Media/Images",
    '.psd': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Media/Images",
    '.svg': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Media/Images",
    '.tif': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Media/Images",
    '.tiff': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Media/Images",
    '.CR2': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Media/Images",
    # Internet
    '.asp': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Other/Internet",
    '.aspx': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Other/Internet",
    '.cer': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Other/Internet",
    '.cfm': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Other/Internet",
    '.cgi': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Other/Internet",
    '.pl': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Other/Internet",
    '.css': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Other/Internet",
    '.htm': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Other/Internet",
    '.js': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Other/Internet",
    '.jsp': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Other/Internet",
    '.part': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Other/Internet",
    '.php': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Other/Internet",
    '.rss': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Other/Internet",
    '.xhtml': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Other/Internet",
    # Compressed
    '.7z': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Other/Compressed",
    '.arj': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Other/Compressed",
    '.deb': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Other/Compressed",
    '.pkg': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Other/Compressed",
    '.rar': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Other/Compressed",
    '.rpm': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Other/Compressed",
    '.tar.gz': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Other/Compressed",
    '.z': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Other/Compressed",
    '.zip': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Other/Compressed",
    # Disc
    '.bin': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Other/Disc",
    '.dmg': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Other/Disc",
    '.iso': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Other/Disc",
    '.toast': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Other/Disc",
    '.vcd': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Other/Disc",
    # Data
    '.csv': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Programming/Database",
    '.dat': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Programming/Database",
    '.db': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Programming/Database",
    '.dbf': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Programming/Database",
    '.log': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Programming/Database",
    '.mdb': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Programming/Database",
    '.sav': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Programming/Database",
    '.sql': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Programming/Database",
    '.tar': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Programming/Database",
    '.xml': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Programming/Database",
    '.json': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Programming/Database",
    # Executables
    '.apk': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Other/Executables",
    '.bat': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Other/Executables",
    '.com': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Other/Executables",
    '.exe': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Other/Executables",
    '.gadget': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Other/Executables",
    '.jar': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Other/Executables",
    '.wsf': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Other/Executables",
    # Fonts
    '.fnt': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Other/Fonts",
    '.fon': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Other/Fonts",
    '.otf': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Other/Fonts",
    '.ttf': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Other/Fonts",
    # Presentations
    '.key': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Text/Presentations",
    '.odp': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Text/Presentations",
    '.pps': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Text/Presentations",
    '.ppt': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Text/Presentations",
    '.pptx': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Text/Presentations",
    # Programming
    '.c': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Programming/C&C++",
    '.class': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Programming/Java",
    '.dart': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Programming/Dart",
    '.py': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Programming/Python",
    '.sh': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Programming/Shell",
    '.swift': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Programming/Swift",
    '.html': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Programming/C&C++",
    '.h': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Programming/C&C++",
    # Spreadsheets
    '.ods': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Text/Microsoft/Excel",
    '.xlr': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Text/Microsoft/Excel",
    '.xls': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Text/Microsoft/Excel",
    '.xlsx': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Text/Microsoft/Excel",
    # System
    '.bak': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Text/Other/System",
    '.cab': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Text/Other/System",
    '.cfg': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Text/Other/System",
    '.cpl': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Text/Other/System",
    '.cur': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Text/Other/System",
    '.dll': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Text/Other/System",
    '.dmp': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Text/Other/System",
    '.drv': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Text/Other/System",
    '.icns': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Text/Other/System",
    '.ini': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Text/Other/System",
    '.lnk': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Text/Other/System",
    '.msi': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Text/Other/System",
    '.sys': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Text/Other/System",
    '.tmp': "/Users/KOMFUEKU METH. PRY/Projects/demos/cat-test/Text/Other/System",
}
